import { Button, VerticalBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    height: 500px;
    width: 500px;
    GridLayout {
        spacing: 5px;
        Row {
            Rectangle {
                width: 200px;
                height: 200px;
                background: blue;
                border-color: orange;
                border-radius: 10px;
                
                Text {
                    text: "hello world";
                    color: green;
                    font-size: 24px;
                }
            }
        }
        Row {
            Rectangle { 
                width: 200px;
                height: 200px;
                background: red; 
                Button {
                    in-out property <bool> is_clicked: false;
                    in-out property <string> label_text: "";
                    width: 200px;
                    height: 200px;
                    text: "click the button";
                    clicked => {
                        if (is_clicked) { 
                            label_text= "the button is clicked";
                        } else { 
                            label_text= "the button is not clicked";
                        }

                        label.text = label_text;
                        is_clicked= !is_clicked;

                    }
                }
            }
            Rectangle { 
            background: green; 
            label := Text { 
                text: "not clicked";
            }
            
        }
        }
        
    }
    
}
